import { useEffect, useState } from 'react';
import { Check, ArrowDown } from 'lucide-react';
import Decimal from 'decimal.js';
import { conversionFactor } from './conversion';
import { api } from './api';
import { EvidenceDrawer } from './History';
import { type Line, type Suggestion } from './types';
export function MappingPanel({ line, busy, onApply, onConfirm, onReject, onConvert, onCancelConversion }: { line: Line; busy: boolean; onConvert?:(unit:string)=>Promise<void>; onCancelConversion?:()=>Promise<void>; onReject?:(s:Suggestion)=>Promise<void>; onApply: (s: Suggestion) => Promise<void>; onConfirm: (code: string, original: string, unit: string) => Promise<void> }) {
  const [evidence, setEvidence] = useState('');
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [code, setCode] = useState(line.sistela_code); const [original, setOriginal] = useState(line.sistela_original_description); const [unit, setUnit] = useState(line.unit); const [error, setError] = useState('');
  useEffect(() => { setCode(line.sistela_code); setOriginal(line.sistela_original_description); setUnit(line.review_data?.conversion?.confirmed_by_user ? line.review_data.conversion.target_unit : line.unit); setError(''); let cancelled = false;
    void api<Suggestion[]>(`/projects/${line.project_id}/lines/${line.id}/suggestions`).then(s => { if (!cancelled) setSuggestions(s); }).catch(e => { if (!cancelled) setError(e.message); }); return () => { cancelled = true; };
  }, [line.id, line.version, line.project_id, line.sistela_code, line.sistela_original_description, line.unit]);
  const factor=conversionFactor(line.unit,unit);
  if (line.line_type !== 'Work') return <div className="mapping-material"><Check size={16}/><p>Medžiagos eilutė.<br/>Darbų normatyvas nepriskiriamas.</p></div>;
  return <div className="mapping-panel"><div className="panel-kicker">NORMATYVO PARINKIMAS</div>
    {suggestions.length > 0 ? suggestions.map(s => <div key={s.mapping_id} className="suggestion"><div><strong>{s.sistela_code}</strong><span className={`confidence ${Number(s.confidence) >= .9 ? 'high' : Number(s.confidence) >= .7 ? 'medium' : 'low'}`}>{Number(s.confidence) >= .9 ? 'High' : Number(s.confidence) >= .7 ? 'Medium' : 'Low'}</span></div><p>{s.sistela_description || 'Originalus pavadinimas nežinomas'}</p><small>{s.method === 'exact' ? 'Tikslus tekstas' : s.method === 'normalized' ? 'Normalizuotas tekstas' : 'Panašus tekstas'} · {s.confirmed_count} patvirtinimai · {s.source_unit}</small><button disabled={!s.compatible || busy} onClick={() => void onApply(s).catch(() => {})}><ArrowDown size={13}/> Pasirinkti kodą</button>{onReject&&<button disabled={busy} onClick={()=>void onReject(s).catch(()=>{})}>Atmesti šį pasiūlymą</button>}{s.origin === 'catalog'&&<p>Šaltinis: normatyvų katalogas.</p>}{s.origin === 'user'&&<p>Šaltinis: ankstesni vartotojo pasirinkimai.</p>}{s.historical_confirmed&&<p>Patvirtinta istorinė patirtis</p>}{onConvert&&conversionFactor(line.unit,s.source_unit)&&<button disabled={busy} onClick={()=>setUnit(s.source_unit)}>Peržiūrėti konversiją į {s.source_unit}</button>}{s.origin === 'historical' && <details><summary>Istoriniai įrodymai · {s.usage_count} panaudojimai</summary><p>{s.project_count} objektų · {s.estimate_count} sąmatų · {s.confirmed_count} žmogaus patvirtinimai</p><p>{s.matching_descriptions?.join(' · ')}</p><p>Įrodymai: {s.evidence_quality?.join(', ')}</p><p>Archyve įrašyta data: {s.source_date || 'nežinoma'} (nepatvirtina panaudojimo datos)</p>{s.evidence_ids?.map((id,i) => <button key={id} onClick={() => setEvidence(id)}>Atverti šaltinį {i+1}</button>)}</details>}{!s.compatible && <p className="error-text">Nesuderinti vienetai arba neaiškus įrodymas. Pasiūlymo taikymas blokuotas.{s.unit_compatibility?.status === 'CONVERTIBLE' && <> Aiški taisyklė: kiekis × {s.unit_compatibility.factor}; {s.unit_compatibility.source} → {s.unit_compatibility.target}. Atverkite Peržiūrą ir aiškiai patvirtinkite konversiją.</>}</p>}</div>) : <p className="muted">Patvirtintų atitikmenų dar nėra. Pasirinkite kodą SISTELA programoje – šį pasirinkimą prisiminsime.</p>}
    {onConvert&&factor&&<div className="conversion-review"><strong>Aiški vienetų konversija</strong><p>{line.quantity} {line.unit} → {new Decimal(line.quantity).times(factor).toFixed()} × {unit}</p><button disabled={busy} onClick={()=>void onConvert(unit).catch(()=>{})}>Patvirtinti konversiją</button><small>Projekto kiekis lieka nepakeistas. Konversija taikoma tik aiškiai ją patvirtinus.</small></div>}
    {onCancelConversion&&line.review_data?.conversion&&<button disabled={busy} onClick={()=>void onCancelConversion().catch(()=>{})}>Atšaukti konversiją, naudoti projekto vienetą</button>}
    <form onSubmit={e => { e.preventDefault(); void onConfirm(code, original, unit).catch(() => {}); }}><label>SISTELA normatyvo kodas<input aria-label="Patvirtinamas SISTELA kodas" value={code} onChange={e => setCode(e.target.value)} required/></label><label>Originalus normatyvo pavadinimas<textarea aria-label="Originalus normatyvo pavadinimas" placeholder="Jei žinomas. Galutinio teksto nekeičia." value={original} onChange={e => setOriginal(e.target.value)}/></label><label>Patikrintas normatyvo vienetas<input aria-label="Normatyvo vienetas" value={unit} onChange={e => setUnit(e.target.value)} required/></label><button className="primary" disabled={busy || !code.trim()} type="submit"><Check size={14}/> Išsaugoti kodą</button></form>
    {line.mapping_status === 'confirmed' && <p className="confirmation-note"><Check size={13}/> Pasirinkimas patvirtintas ir išsaugotas istorijoje.</p>}
    <p className="fine-print">Atitikimo įvertis yra pagalbinis signalas, ne tikimybė. Galutinis pavadinimas lieka jūsų.</p>{error && <p className="error-text">{error}</p>}
    {evidence && <EvidenceDrawer id={evidence} onClose={() => setEvidence('')}/>}
  </div>;
}
