import { useEffect, useState } from 'react';
import { api, apiUrl, post } from './api';
import { MappingPanel } from './MappingPanel';
import { DbfExport } from './DbfExport';
import type { Line } from './types';
import './workflow.css';

interface ReviewRow {id:string; category:string; issues:{category:string;severity:string;message:string}[]; target_quantity:string;target_unit:string;source_filename:string|null;price_status:string;duplicates:{id:string;key:string}[]}
interface Report {status:string;blocking:number;warnings:number;rows:ReviewRow[];summary:Record<string,number>;statistics:Record<string,number>}
const labels:Record<string,string> = {total:'Eilutės',materials:'Medžiagos',works:'Darbai',mapped:'Su kodu',confirmed:'Patvirtinti normatyvai',unresolved:'Nepatvirtinti darbai',needs_review:'Peržiūrėtinos eilutės',entered:'Suvesta',missing_prices:'Trūksta kainų',confirmed_prices:'Patvirtintos kainos',conversions:'Patvirtintos konversijos'};
const metrics:Record<string,string> = {imported_line_count:'Importuota eilučių',auto_suggested_mapping_count:'Darbai su pasiūlymais',confirmed_without_change_count:'Patvirtinta nekeičiant pasiūlymo',changed_mapping_count:'Pakeisti pasiūlymai',manual_mapping_count:'Rankinis parinkimas',review_issue_count:'Peržiūros klausimai',entry_mode_completed_count:'Suvesti darbai'};

export function Workflow({projectId,lines,ready,busy,onChange,onEntry,onGrid}:{projectId:string;lines:Line[];ready:boolean;busy:boolean;onChange:(job:()=>Promise<Line[]>)=>Promise<void>;onEntry:()=>void;onGrid:(id:string)=>void}) {
  const [report,setReport]=useState<Report>(); const [id,setId]=useState(''); const [all,setAll]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false; void api<Report>(`/projects/${projectId}/validation`).then(r=>{if(!cancelled)setReport(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[projectId,lines]);
  const rows=report?.rows.filter(r=>all||r.issues.length)||[];
  const selected=rows.find(r=>r.id===id)||rows[0]; const line=lines.find(l=>l.id===selected?.id);
  async function mutate(path:string,body:object) {if(!line)return;setError('');try{await onChange(async()=>{await post(`/projects/${projectId}/lines/${line.id}/${path}`,{version:line.version,...body});return api<Line[]>(`/projects/${projectId}/lines`);});}catch(e){setError((e as Error).message);}}
  async function validate(){try{setReport(await post<Report>(`/projects/${projectId}/validate`));setError('');}catch(e){setError((e as Error).message);}}

  return <section className="workflow"><header><p className="eyebrow">PROJEKTAS → IMPORTAS → PERŽIŪRA → NORMATYVAI → VALIDACIJA</p><h2>{ready?'Paruošta SISTELA':'Peržiūra · Review Queue'}</h2><p role="status">{report?.status} · Blokuoja: {report?.blocking} · Įspėjimai: {report?.warnings}</p><button className="primary" disabled={busy} onClick={()=>void validate()}>Patikrinti parengtį</button></header>
    {error&&<p role="alert">{error}</p>}
    {ready ? <><div className="workflow-summary">{Object.entries(report?.summary||{}).map(([key,value])=><div key={key}><strong>{value}</strong><span>{labels[key]||key}</span></div>)}</div><div className="workflow-actions"><button onClick={()=>{setAll(false);onGrid('review');}}>Peržiūrėti klausimus</button><button disabled={!report||report.blocking>0} onClick={onEntry}>Atverti SISTELA Entry Mode</button>{report&&report.blocking===0&&<a className="button" href={apiUrl(`/projects/${projectId}/export.xlsx`)}>Eksportuoti darbinę sąmatą XLSX</a>}<button disabled>Experimental SISTELA TXT</button></div><DbfExport projectId={projectId}/><p>Darbinė sąmata ir pagalba rankiniam suvedimui. Tai nėra patvirtintas automatinis importas ar galutinė komercinė SISTELA sąmata.</p></> : <><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> Rodyti ir paruoštas eilutes</label><div className="review-layout"><nav aria-label="Peržiūros eilutės">{rows.map(r=><button className={r.id===line?.id?'selected':''} key={r.id} onClick={()=>setId(r.id)}><strong>{lines.find(l=>l.id===r.id)?.project_description}</strong><small>{r.category}</small><span>{r.issues.some(i=>i.severity==='BLOCKING')?'Blokuoja':r.issues.length?'Įspėjimas':'Paruošta'}</span></button>)}{!rows.length&&<p>Peržiūros klausimų nėra.</p>}</nav>{line&&selected&&<article><h3>{line.project_description}</h3><p>Projektas: {line.quantity} {line.unit} → SISTELA: {selected.target_quantity} {selected.target_unit}</p><p>Būsena: {line.mapping_status}{line.review_data?.manual?' · Rankinis parinkimas':''}</p>{selected.issues.map((i,index)=><p className={i.severity==='BLOCKING'?'error-text':'muted'} key={index}>{i.severity}: {i.message}</p>)}<button onClick={()=>onGrid(line.id)}>Redaguoti lentelėje / sujungti rankiniu būdu</button>
      {selected.duplicates.map(d=><div key={d.key}><button disabled={busy} onClick={()=>void mutate('review',{action:'keep_both',duplicate_id:d.id})}>Palikti abu / atmesti dublikato įspėjimą</button></div>)}
      {line.line_type==='Work'&&<><MappingPanel key={line.id} line={line} busy={busy} onConvert={unit=>mutate('review',{action:'convert',target_unit:unit})} onCancelConversion={()=>mutate('review',{action:'cancel_conversion'})} onReject={s=>mutate('review',{action:'reject',mapping_id:s.mapping_id})} onApply={s=>mutate('mapping/apply',{mapping_id:s.mapping_id})} onConfirm={(code,original,unit)=>mutate('mapping/confirm',{sistela_code:code,sistela_original_description:original,normative_unit:unit})}/><div className="workflow-actions"><button disabled={busy} onClick={()=>void mutate('review',{action:'reject'})}>Atmesti pasirinktą pasiūlymą</button><button disabled={busy} onClick={()=>void mutate('review',{action:'manual'})}>Parinksiu rankiniu būdu</button></div></>}
      <label>Kainos būsena<select aria-label="Kainos būsena" value={selected.price_status} disabled={busy} onChange={e=>void mutate('review',{action:'price',price_status:e.target.value})}>{['MISSING','ENTERED','HISTORICAL_REFERENCE','CONFIRMED'].map(s=><option key={s}>{s}</option>)}</select></label>
      <details className="source-detail"><summary>Dabartinio projekto šaltinis</summary><p>{selected.source_filename||'Rankinė eilutė'} · {line.source_page?`PDF p. ${line.source_page}`:'Excel / rankinis šaltinis'}</p><pre>{line.source_raw_text||'Šaltinio nėra'}</pre></details></article>}</div></>}
    <details className="workflow-statistics"><summary>Workflow statistics · vietinė darbo statistika</summary><dl>{Object.entries(report?.statistics||{}).map(([key,value])=><div key={key}><dt>{metrics[key]}</dt><dd>{value}</dd></div>)}</dl><p>Dabartinės projekto eilutės ir išsaugoti žmogaus pasirinkimai. Duomenys niekur nesiunčiami; klavišų paspaudimai nerenkami.</p></details>
  </section>;
}
