import { useEffect, useState } from 'react';
import { api, apiUrl, post } from './api';
import { MappingPanel } from './MappingPanel';
import { Export } from './Export';
import type { Line } from './types';
import './workflow.css';

interface ReviewRow {id:string; category:string; issues:{category:string;severity:string;message:string}[]; target_quantity:string;target_unit:string;source_filename:string|null;price_status:string;duplicates:{id:string;key:string}[]}
interface Report {status:string;blocking:number;warnings:number;rows:ReviewRow[];summary:Record<string,number>;statistics:Record<string,number>}
const labels:Record<string,string> = {total:'Eilutės',materials:'Medžiagos',works:'Darbai',mapped:'Su kodu',confirmed:'Patvirtinti normatyvai',unresolved:'Darbai be kodo',needs_review:'Peržiūrėtinos eilutės',entered:'Suvesta',missing_prices:'Trūksta kainų',confirmed_prices:'Patvirtintos kainos',conversions:'Patvirtintos konversijos'};
const metrics:Record<string,string> = {automatic_code_count:'Automatiškai parinkti kodai',corrected_code_count:'Vartotojo pataisyti kodai',imported_line_count:'Importuota eilučių',auto_suggested_mapping_count:'Darbai su pasiūlymais',confirmed_without_change_count:'Patvirtinta nekeičiant pasiūlymo',changed_mapping_count:'Pakeisti pasiūlymai',manual_mapping_count:'Rankinis parinkimas',review_issue_count:'Peržiūros klausimai',entry_mode_completed_count:'Suvesti darbai'};

export function Workflow({projectId,lines,ready,busy,onChange,onEntry,onGrid,onSettings}:{projectId:string;lines:Line[];ready:boolean;busy:boolean;onChange:(job:()=>Promise<Line[]>)=>Promise<void>;onEntry:()=>void;onGrid:(id:string)=>void;onSettings?:()=>void}) {
  const [report,setReport]=useState<Report>(); const [id,setId]=useState(''); const [all,setAll]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false; void api<Report>(`/projects/${projectId}/validation`).then(r=>{if(!cancelled)setReport(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[projectId,lines]);
  const rows=report?.rows.filter(r=>all||r.issues.length)||[];
  const selected=rows.find(r=>r.id===id)||rows[0]; const line=lines.find(l=>l.id===selected?.id);
  async function mutate(path:string,body:object) {if(!line)return;setError('');try{await onChange(async()=>{await post(`/projects/${projectId}/lines/${line.id}/${path}`,{version:line.version,...body});return api<Line[]>(`/projects/${projectId}/lines`);});}catch(e){setError((e as Error).message);}}


  return <section className="workflow"><header><p className="eyebrow">IMPORTAS → IŠIMČIŲ PERŽIŪRA → EKSPORTAS</p><h2>{ready?'Paruošta SISTELA':'Peržiūra · Review Queue'}</h2><p role="status">{report?.blocking ? `Reikia sutvarkyti ${report.blocking} laukus` : ready ? 'Eksporto parengtis tikrinama automatiškai' : 'Eilutės patikrintos'} · Įspėjimai: {report?.warnings}</p></header>
    {error&&<p role="alert">{error}</p>}
    {ready ? <><div className="workflow-summary">{Object.entries(report?.summary||{}).filter(([key])=>['total','materials','works'].includes(key)).map(([key,value])=><div key={key}><strong>{value}</strong><span>{labels[key]||key}</span></div>)}</div><div className="workflow-actions"><button onClick={()=>{setAll(false);onGrid('review');}}>Peržiūrėti klausimus</button>{report&&report.blocking===0&&<a className="button" href={apiUrl(`/projects/${projectId}/export.xlsx`)}>Eksportuoti darbinę sąmatą XLSX</a>}</div><Export projectId={projectId} onSettings={onSettings} onGrid={onGrid}/><details><summary>Papildomi būdai</summary><p>Rankinis perkėlimas yra neprivalomas atsarginis būdas. Visos sąmatos eksportui jo naudoti nereikia.</p><button onClick={onEntry}>Rankinis perkėlimas</button></details></> : <><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> Rodyti ir paruoštas eilutes</label><div className="review-layout"><nav aria-label="Peržiūros eilutės">{rows.map(r=><button className={r.id===line?.id?'selected':''} key={r.id} onClick={()=>setId(r.id)}><strong>{lines.find(l=>l.id===r.id)?.project_description}</strong><small>{r.issues[0]?.message||'Paruošta'}</small><span>{r.issues.some(i=>i.severity==='BLOCKING')?'Blokuoja':r.issues.length?'Įspėjimas':'Paruošta'}</span></button>)}{!rows.length&&<p>Peržiūros klausimų nėra.</p>}</nav>{line&&selected&&<article><h3>{line.project_description}</h3><p>Projektas: {line.quantity} {line.unit} → SISTELA: {selected.target_quantity} {selected.target_unit}</p><p>Būsena: {{unmapped:'Nepasirinkta',suggested:'Parinkta automatiškai',confirmed:'Išsaugota',rejected:'Atmesta',needs_review:'Reikia peržiūros'}[line.mapping_status]}{line.review_data?.manual?' · Rankinis parinkimas':''}</p>{selected.issues.map((i,index)=><p className={i.severity==='BLOCKING'?'error-text':'muted'} key={index}>{i.severity}: {i.message}</p>)}<button onClick={()=>onGrid(line.id)}>Redaguoti lentelėje / sujungti rankiniu būdu</button>
      {selected.duplicates.map(d=><div key={d.key}><button disabled={busy} onClick={()=>void mutate('review',{action:'keep_both',duplicate_id:d.id})}>Palikti abu / atmesti dublikato įspėjimą</button></div>)}
      {line.line_type!=='Other'&&<><MappingPanel key={line.id} line={line} busy={busy} onConvert={unit=>mutate('review',{action:'convert',target_unit:unit})} onCancelConversion={()=>mutate('review',{action:'cancel_conversion'})} onReject={s=>mutate('review',{action:'reject',mapping_id:s.mapping_id})} onApply={s=>mutate('mapping/select',{mapping_id:s.mapping_id})} onConfirm={(code,original,unit)=>mutate('mapping/confirm',{sistela_code:code,sistela_original_description:original,normative_unit:unit})}/><div className="workflow-actions"><button disabled={busy} onClick={()=>void mutate('review',{action:'reject'})}>Atmesti pasirinktą pasiūlymą</button><button disabled={busy} onClick={()=>void mutate('review',{action:'manual'})}>Parinksiu rankiniu būdu</button></div></>}
      <details><summary>Papildomi peržiūros duomenys</summary><label>Kainos būsena<select aria-label="Kainos būsena" value={selected.price_status} disabled={busy} onChange={e=>void mutate('review',{action:'price',price_status:e.target.value})}>{['MISSING','ENTERED','HISTORICAL_REFERENCE','CONFIRMED'].map(s=><option key={s}>{s}</option>)}</select></label></details>
      <details className="source-detail"><summary>Dabartinio projekto šaltinis</summary><p>{selected.source_filename||'Rankinė eilutė'} · {line.source_page?`PDF p. ${line.source_page}`:'Excel / rankinis šaltinis'}</p><pre>{line.source_raw_text||'Šaltinio nėra'}</pre></details></article>}</div></>}
    <details className="workflow-statistics"><summary>Techninės detalės · darbo statistika</summary><dl>{Object.entries(report?.statistics||{}).map(([key,value])=><div key={key}><dt>{metrics[key]}</dt><dd>{value}</dd></div>)}</dl><p>Dabartinės projekto eilutės ir išsaugoti žmogaus pasirinkimai. Duomenys niekur nesiunčiami; klavišų paspaudimai nerenkami.</p></details>
  </section>;
}
