"""initial_domain"""

import sqlalchemy as sa
from alembic import op

revision = "231609db4375"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("customer", sa.String(), nullable=False),
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sistela_mappings",
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("source_text", sa.String(), nullable=False),
        sa.Column("normalized_source_text", sa.String(), nullable=False),
        sa.Column("sistela_code", sa.String(), nullable=False),
        sa.Column("sistela_description", sa.Text(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.String(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("usage_count >= 0 AND confirmed_count >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_type", "normalized_source_text", "sistela_code"),
    )
    op.create_table(
        "estimate_sections",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "id"),
    )
    op.create_table(
        "source_documents",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "checksum"),
        sa.UniqueConstraint("project_id", "id"),
    )
    op.create_table(
        "estimate_lines",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("line_type", sa.String(), nullable=False),
        sa.Column("source_position", sa.String(), nullable=False),
        sa.Column("project_description", sa.Text(), nullable=False),
        sa.Column("technical_reference", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("quantity", sa.Text(), nullable=False),
        sa.Column("sistela_code", sa.String(), nullable=False),
        sa.Column("sistela_original_description", sa.Text(), nullable=False),
        sa.Column("output_description", sa.Text(), nullable=False),
        sa.Column("material_price", sa.Text(), nullable=True),
        sa.Column("work_price", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Text(), nullable=True),
        sa.Column("mapping_status", sa.String(), nullable=False),
        sa.Column("source_document_id", sa.String(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_raw_text", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("line_type IN ('Material','Work','Other')"),
        sa.CheckConstraint("mapping_status IN ('unmapped','suggested','confirmed')"),
        sa.CheckConstraint("source_page IS NULL OR source_page > 0"),
        sa.ForeignKeyConstraint(
            ["project_id", "section_id"],
            ["estimate_sections.project_id", "estimate_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "source_document_id"],
            ["source_documents.project_id", "source_documents.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "id"),
    )
    op.create_index(
        "ix_lines_project_order", "estimate_lines", ["project_id", "sort_order"], unique=False
    )
    op.create_table(
        "import_runs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("rows_detected", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("pages", sa.JSON(), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("status IN ('running','completed','needs_review','failed')"),
        sa.ForeignKeyConstraint(
            ["project_id", "source_document_id"],
            ["source_documents.project_id", "source_documents.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requirements",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("related_estimate_line_id", sa.String(), nullable=True),
        sa.Column("source_document_id", sa.String(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("requirement_text", sa.Text(), nullable=False),
        sa.Column("requirement_type", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "related_estimate_line_id"],
            ["estimate_lines.project_id", "estimate_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "source_document_id"],
            ["source_documents.project_id", "source_documents.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requirements")
    op.drop_table("import_runs")
    op.drop_index("ix_lines_project_order", table_name="estimate_lines")
    op.drop_table("estimate_lines")
    op.drop_table("source_documents")
    op.drop_table("estimate_sections")
    op.drop_table("sistela_mappings")
    op.drop_table("projects")
    # ### end Alembic commands ###
