"""historical_knowledge"""

import sqlalchemy as sa
from alembic import op

revision = "66611011cc47"
down_revision = "003_import_selection"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_imports",
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("source_reference", sa.String(), nullable=False),
        sa.Column("source_files", sa.JSON(), nullable=False),
        sa.Column("encoding", sa.String(), nullable=False),
        sa.Column("imported_at", sa.String(), nullable=False),
        sa.Column("import_status", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_hash"),
    )
    op.create_table(
        "historical_estimates",
        sa.Column("historical_import_id", sa.String(length=36), nullable=False),
        sa.Column("external_key", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("system_evidence", sa.String(), nullable=False),
        sa.Column("source_date", sa.String(), nullable=True),
        sa.Column("source_reference", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["historical_import_id"],
            ["historical_imports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_estimates_historical_import_id"),
        "historical_estimates",
        ["historical_import_id"],
        unique=False,
    )
    op.create_table(
        "historical_lines",
        sa.Column("historical_estimate_id", sa.String(length=36), nullable=False),
        sa.Column("external_key", sa.JSON(), nullable=False),
        sa.Column("line_type", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("normalized_description", sa.String(), nullable=False),
        sa.Column("sistela_code", sa.String(), nullable=False),
        sa.Column("sistela_original_description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("quantity", sa.Text(), nullable=True),
        sa.Column("historical_price", sa.Text(), nullable=True),
        sa.Column("section_name", sa.String(), nullable=False),
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("evidence_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.String(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("evidence_type IN ('DIRECT','DERIVED','AMBIGUOUS')"),
        sa.CheckConstraint("status IN ('CANDIDATE','CONFIRMED','REJECTED','NOT_APPLICABLE')"),
        sa.ForeignKeyConstraint(
            ["historical_estimate_id"],
            ["historical_estimates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_lines_historical_estimate_id"),
        "historical_lines",
        ["historical_estimate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_lines_normalized_description"),
        "historical_lines",
        ["normalized_description"],
        unique=False,
    )
    op.create_table(
        "historical_reviews",
        sa.Column("historical_line_id", sa.String(length=36), nullable=False),
        sa.Column("previous_status", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("system_type", sa.String(), nullable=False),
        sa.Column("acknowledged_ambiguity", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["historical_line_id"],
            ["historical_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_reviews_historical_line_id"),
        "historical_reviews",
        ["historical_line_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historical_reviews_historical_line_id"), table_name="historical_reviews")
    op.drop_table("historical_reviews")
    op.drop_index(op.f("ix_historical_lines_normalized_description"), table_name="historical_lines")
    op.drop_index(op.f("ix_historical_lines_historical_estimate_id"), table_name="historical_lines")
    op.drop_table("historical_lines")
    op.drop_index(
        op.f("ix_historical_estimates_historical_import_id"), table_name="historical_estimates"
    )
    op.drop_table("historical_estimates")
    op.drop_table("historical_imports")
    # ### end Alembic commands ###
